apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backend
  labels:
    app: backend
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
  labels:
    app: nginx

