apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nginx-build
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/Uliwazeer/Project3-3tier-App.git
    contextDir: nginx
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: nginx:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
